### PR TITLE
qbit dark webui

### PR DESCRIPTION
**Pull request by brettpetch**
added install for dark theme provided by https://github.com/repslet/nightwalker.git

## Fixes issues: 
- N/A

## Proposed Changes:
- Dark theme for qbit

## Categories
- New feature (non-breaking change which adds functionality)

## Architectures
- `x86_64` is specifically handled as:
    - [x] Success
- `arm64` is specifically handled as:
    - Notes: Unknown.
- [x] Changes are arch agnostic 

## Checklist

- [x] Docs have been made OR are not necessary
- [x] Changes to panel have been made OR are not necessary
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas

## Testing done
OS & Version: Debian 10

### How have you tested this

Scenarios tested:
- I ran this and it worked

## Other remarks
None.

### CODE REVIEW

**Comment by flying-sausages** [comment]
I took the liberty of updating the PR statement, will check this in a bit

**Comment by brettpetch** [comment]
Thanks sausages!

**Comment by repslet** [comment]
Thanks for this PR @brettpetch.
New "feature" is colored ratios, like the rutorrent theme.

**Comment by liaralabs** [comment]
Theme works great and looks good. Thanks for the awesome work!

I do have some questions:

- Should this be default? If no, how do we go about this
- If this is default, we need to assist folks with an `update` script to help pull in the new config default

**Comment by brettpetch** [comment]
I think this (should) be safe for default, although our lead dev would need to make sure. If it doesn't work with the latest I'll look into the logic when we get a response from @repslet to see what we can do. I'll write an update script and add it in later in the week.

Thanks for the response @liaralabs

**Comment by flying-sausages** [comment]
If the system-aware theme switching is possible (i.e. turns dark when dark mode turns on on the device) I'd be happy to make it default from the "usability" pov.

Then again, we already do change the default theme of rutorrent anyway, so i suppose we should think what the arguments for that are/were too.

I guess one huge thing we absolutely need to consider is support and maintenance going forward though. we can't default something which could break/be missing features when people upgrade to newer qbits on day 0.

I'm wondering if this should be implemented through an "app installer" which would require qbit to be installed instead. Or maybe start maintaining something `qtx` next to `rtx` for rutorrent extension manager. After all you suggest a clone to `/opt/` which implies a different app. The updating for _just_ the theme will become  lot easier too, and people will have to add and remove it as they want with a clean interface.

**Comment by brettpetch** [comment]
I’ll make a pull request to the project and see if I can implement the light theme — it should be possible to set a light and dark theme quite easily. 

After some review, it appears as though the theme is not compatible with qbit 4.1.x so a filter in the config will be necessary to check version against those that are compatible with the theme. 

As for reverting the changes, it would be as easy as setting webui\alternativewebinterface to false. 

I’ll look into RTX this week and do some digging to see if QTX is a possibility for the implementation of themes. One of the previous themes I’ve tried with qbit tried registered a service worker to the web browser, which would make it quite annoying trying to get rid of it — so unregistering service workers may be something for us to look into as well during the development process which I don’t know a whole lot about and further research into the area would be needed. 

@repslet what is your strategy for maintenance? Are day0 updates going to be available?

**Comment by brettpetch** [comment]
going to move as it's own app over the next couple days.

**Comment by flying-sausages** [comment]
yo any movement on this?

**Comment by brettpetch** [comment]
Haven't heard from the dev after 1.0 release. In limbo atm.

**Comment by repslet** [comment]
> yo any movement on this?

Yep, next version will be a system aware theme. I've got it working for qbit 4.3.2. But I noticed a new version of the WebUI just got released with new settings. Need to merge those with my theme


> Haven't heard from the dev after 1.0 release. In limbo atm.
I've been extremely busy with the vaccine rollout. Next theme update will be coming soon ;)

**Comment by flying-sausages** [comment]
> I've been extremely busy with the vaccine rollout. Next theme update will be coming soon ;)

Honourable! take your time :)

**Pull request closed without merging**
