### PR TITLE
Swizzin file-based "quasi-DB"

### PR DESCRIPTION
**Pull request by flying-sausages**
## Fixes issues: 
- We don't have a place to store values
- We resorted to using lockfiles, .info files in `root`, and many others and it's now messy

## Proposed Changes:
- Start using `/var/lib/swizzin/db` for storing "values" in files named by the keys

## Categories

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Some existing `functions` got changed (e.g. `utils`, `os`, `apt`, `ask`, etc.)
- Changes structure of project (major rewrites, large directory changes, etc.)

## Architectures

- `x86_64` is specifically handled as:
    - [ ] Success
    - [ ] Error
    - Notes: 
- `arm64` is specifically handled as:
    - [ ] Success
    - [ ] Error
    - Notes: 
- [x] Changes are arch agnostic 
    - Notes: nothing but unix baby

## Checklist

- [x] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas

## Testing done
OS & Version: Ubuntu 20.04 for ARM

### How have you tested this

Scenarios tested:
- I ran this and it worked
- I ran that and it didn't work

## Other remarks

afbeelding

### CODE REVIEW

**Review by liaralabs — APPROVED** [review]
Looks good to me

**Comment by flying-sausages** [comment]
@liaralabs any good thoughts on what to rename this to properly?

**Comment by liaralabs** [comment]
Hmm yeah. The naming did stick out to me as being something I'm not super in love with. Tbh I don't mind just `swizzin_db` or maybe even `swizzin_var(s)`.

Would it be a hassle to reorganzie the structure so the commands would be more along the lines of:

```
swizzin_db get
swizzin_db set
```

This way perhaps feels a little more readable to me

**Comment by flying-sausages** [comment]
I'll slap a wrapper function in front of it then real fast

**Comment by flying-sausages** [comment]
@liaralabs I'm happy with this now
image

**Comment by liaralabs** [comment]
Looks good to me if you're ready to merge

**Pull request merged**
