### PR TITLE
fix(filebrowser): arm-compatibility & code style

### LINKED ISSUE #758: [BUG] File browser 502 Bad Gateway on Ubuntu 20.04 (arm64)
### What happened?

Steps to reproduce:

Fresh install of Ubuntu 20.04.

Install package filebrowser,
Go to filebrowser web panel
Error 502 Bad Gateway nginx
While other services like qbittorrent works fine

Expected results:
working web panel of filebrowser

### Swizzin commit

6f07eb7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

arm64

### Relevant logs and output

```plaintext
systemd[26669]: filebrowser.service: Failed to execute command: Exec format error
systemd[26669]: filebrowser.service: Failed at step EXEC spawning /home/username/bin/filebrowser: Exec format error
systemd[1]: filebrowser.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: filebrowser.service: Failed with result 'exit-code'.

/etc/systemd/system# cat filebrowser.service
[Unit]
Description=filebrowser
After=network.target

[Service]
User=username
Group=username
UMask=002

Type=simple
WorkingDirectory=/home/username
ExecStart=/home/username/bin/filebrowser -d /home/username/.config/Filebrowser/filebrowser.db
TimeoutStopSec=20
KillMode=process
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
```

### PR DESCRIPTION
**Pull request by flying-sausages**
## Description
Enables multi-arch installs, cleans up legacy formatting

## Fixes issues: 
Fixes #758

## Proposed Changes:
- fix: arch detection
- fix: splitting download logic
- fix: split into functions
- fix: formatting
- fix: function reuse, tigher permissions

## Change Categories
- Bug fix 

## Checklist

- [x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [x] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Testing was done
   - [x] Tests created or no new tests necessary
   - [x] Tests executed

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Focal 		|			|			|	yeah		|				|
| Bionic		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### CODE REVIEW

**Comment by flying-sausages** [comment]
@userdocs please let me know if you still find these legible!

**Comment by liaralabs** [comment]
What about the upgrade script?

**Comment by flying-sausages** [comment]
🥴 oops

**Comment by brettpetch** [comment]
@liaralabs is this good to merge?

**Review by brettpetch — APPROVED** [review]

**Pull request merged**
