### PR TITLE
feat(box): stay on develop over `box update` runs, allow auto-testing

### PR DESCRIPTION
**Pull request by flying-sausages**
## Description
Users on `develop` should be able to stay there over `box update` runs and not be forced to master. Furthermore, in order for this branch to give us some real beenfit, might as well run tests on these setups by default.

## Fixes issues: 
- More feedback from non-standard users
- Automtaic tests when on "dev" setup

## Proposed Changes:
All previous "not updating" scenarios will now additionally run tests on **all** box functions (help, list and invalid args excluded)

## Change Categories

- New feature 
- Breaking change 
- Change in `functions` 
- Project structure 

## Checklist

- [x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [x] Docs have been made OR are not necessary
    - PR link: https://github.com/liaralabs/docs.swizzin.ltd/pull/93
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Testing was done
   - [x] Tests created or no new tests necessary
   - [x] Tests executed

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Focal 		|			|			|			|				|
| Bionic		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### CODE REVIEW

**Comment by liaralabs** [comment]
The way you've structured this, all the branch code will run and echo during every box run, even for functions which don't touch git at all (like install and remove). I don't think this is ideal, especially considering the warnings have not been updated to reflect that this code runs during every `box` run. Ideally I'd like to see this cleaned up so that code isn't being run if it doesn't need to be.

**Comment by flying-sausages** [comment]
> The way you've structured this, all the branch code will run and "relevant" `echo_warns` will be displayed during every box run, even for functions which don't touch git at all (like install and remove). I don't think this is ideal, especially considering the warnings have not been updated to reflect that this code runs during every `box` run.

I cleaned the echos up and only show them in the update function

>  Ideally I'd like to see this cleaned up so that code isn't being run if it doesn't need to be.

Not sure i interpreted that correctly but I further removed the testing from some functions where I thought it made no sense, or added some reasons for why it should be ran also for legibility

**Comment by liaralabs** [comment]
I don't see much wrong with this PR other than the original feedback that was given for this PR. The bulk of this PR resides outside of the update function which means this new code will run for every user on every instance of calling `box`. Output will not always be made, however, this is not desirable and I would like to see these checks moved back to the update function itself.

I also don't know if the FYI is necessary -- we could simplify it simply by saying which branch will be updated to when running `box update` i.e. `swizzin will be updated from the develop branch` or something along those lines.

**Comment by flying-sausages** [comment]
@liaralabs that feedback was implemented, let me know if you think these are adequate now

**Comment by liaralabs** [comment]
Can you just rebase this PR before we squash? I'm seeing some references without bullseye in the patches and don't want to accidentally revert something here.

**Comment by flying-sausages** [comment]
Rebased!

**Comment by flying-sausages** [comment]
🎉

**Pull request merged**
