### PR TITLE
fix(swizdb): ensure key dirs get returned in path calls

### PR DESCRIPTION
**Pull request by flying-sausages**
## Fixes issues: 
- `swizdb` path changing behaviour since the switch from `-e`

image

## Proposed Changes:
- Add exit code 2 to `swizdb path` when a directory is encountered as key
   - BUT still echo the full path of the dir
   - rest of the functions continue to work as intended
- Add trailing slash to the return of `swizdb path` when a directory is encountered.

## Change Categories

- Bug fix 
- Breaking change 

## Checklist

- [x] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have functionally tested the changes being introduced

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Focal 		|			|			|	✅ 		|				|
| Bionic		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### ✅❎ Passed
image

image

### CODE REVIEW

**Comment by flying-sausages** [comment]
@userdocs some feedback on this would be appreciated!

**Comment by liaralabs** [comment]
Should `_clearswizdb` still rely on an exit code of not 1 to continue? Currently there would be no way to remove a swizdb path if things are nested under a sub-directory it seems

**Comment by userdocs** [comment]
the pull request fixed the stat error for me.

**Comment by flying-sausages** [comment]
> Should `_clearswizdb` still rely on an exit code of not 1 to continue? Currently there would be no way to remove a swizdb path if things are nested under a sub-directory it seems (i.e. `bash_completion`)

If we want recursive deletion I can change that yeah. I originally intended it for individual keys but this could be a nice use case.

If that's the case I might change the variable names inside to reflect it as a dir is not a key.

**Pull request merged**
