### PR TITLE
Queue apps for deletion and removal from the project

### PR DESCRIPTION
**Pull request by liaralabs**
## Description
Remove outdated/unmaintained/unused applications. Generally speaking, applications requiring python2.7 with no support of python3 in sight are top contenders. For this reason PyLoad has been spared (the ng branch is under development and the stable branch is still receiving maintenance)

## Fixes issues: 
Working towards removing python2.7 from the project

## Proposed Changes:
Remove couchpotato (python2.7 app, non maintained)
Remove subsonic (installer seems to be broken)
Remove headphones (python2.7 app, non maintained)

## Change Categories

- App Removal

## Checklist

- [x] Docs have been made OR are not necessary
    - PR link: https://github.com/liaralabs/docs.swizzin.ltd/pull/68
- [ ] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)

## Test scenarios
It's a delete fam

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Focal 		|			|			|			|				|
| Bionic		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### CODE REVIEW

**Comment by brettpetch** [comment]
do it

**Comment by flying-sausages** [comment]
Do we want to remove the nginx and update scripts too?

**Comment by liaralabs** [comment]
I spaced on the nginx scripts but I'm on the fence regarding the update scripts.

I think I'd rather leave them for the time being and then deprecate them together with the remove scripts a bit further off into the future.

**Comment by flying-sausages** [comment]
Docs PR added https://github.com/liaralabs/docs.swizzin.ltd/pull/68

**Comment by flying-sausages** [comment]
> I spaced on the nginx scripts but I'm on the fence regarding the update scripts.
> 
> I think I'd rather leave them for the time being and then deprecate them together with the remove scripts a bit further off into the future.

IIRC we decided that we'd keep all removers forever, CSF and Sonarr v2 removers being examples thereof.

Updaters could be required indeed, as the removers might be dependent on some of the changes they make.

I don't think the panel needs changes for this PR actually.

**Comment by flying-sausages** [comment]
I took the liberty to remove the nginx scripts for the three offenders, so I think this is good to go.

Might want to merge this against a `v3` branch that will also include the sonarr v2 removal and the readme version bump

**Review by flying-sausages — APPROVED** [review]

**Comment by flying-sausages** [comment]
By the way, I think we should first add an alternative to subsonic before getting rid of it https://github.com/swizzin/swizzin/pull/460

**Comment by brettpetch** [comment]
> By the way, I think we should first add an alternative to subsonic before getting rid of it #460

Are the other media servers not suitable replacements? I thought Plex, JF, and Emby all had these integrations.

**Review by brettpetch — APPROVED** [review]

**Comment by flying-sausages** [comment]
They're pretty overkill for just listening to music I would say

**Comment by flying-sausages** [comment]
fuck it let's just go already

**Pull request merged**
