### PR TITLE
fix(mango): update config to match upstream version

### PR DESCRIPTION
**Pull request by rubysamurai**
## Description

This commit updates Mango config to fix the following errors and warnings:

**New entry:** `plugin_path: $mangodir/plugins`
**Fixes:** `[ERROR] Unable to create directory: '/opt/mango/mango': File exists`

**New entry:** `library_cache_path: $mangodir/.config/mango/library.yml.gz`
**Fixes:**
```
Unhandled exception in spawn: Error opening file with mode 'w': '/opt/mango/mango/library.yml.gz': Not a directory (File::Error)
   from usr/share/crystal/src/crystal/system/unix/file.cr:11:7 in 'open'
   from usr/share/crystal/src/file.cr:112:5 in '->'
   from usr/share/crystal/src/primitives.cr:255:3 in 'run'
   from ???
```

**Update entry:** `mangadex.api_url: https://api.mangadex.org/v2`
**Fixes:** `WARN - It looks like you are using the deprecated MangaDex API v1 in your config file.`

## Fixes issues: 
- Un-tracked issue

## Proposed Changes:
- Always re-create config file upon upgrading to match [upstream version example](https://github.com/hkalexling/Mango#config).
- Update install and upgrade scripts to use a `_mkconf_mango` function to simplify maintainability.

## Change Categories

- Bug fix 

## Checklist

- [x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [x] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Testing was done
   - [x] Tests created or no new tests necessary
   - [ ] Tests executed

## Test scenarios

I tested these changes on my Swizzin install on Debian 11 (Bullseye) with no errors/warnings.

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Focal 		|			|			|			|				|
| Bionic		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### CODE REVIEW

**Comment by brettpetch** [comment]
Do you know if the upstream has an updater in place for current installs?

/b

**Comment by rubysamurai** [comment]
From what I can tell by looking at their [source code here](https://github.com/hkalexling/Mango/blob/8a732804ae05d4480afd0646445acabc6808bdce/src/config.cr#L55) config.yml is never updated when it exists, only created when missing.

**Comment by rubysamurai** [comment]
Is `scripts/upgrade/mango.sh` or `scripts/update/mango.sh` would be a proper place for these config injections? 

Would it be ok to group it under the existing Mango fixes in [update/mango.sh](https://github.com/swizzin/swizzin/blob/master/scripts/update/mango.sh#L13)? Or upgrade script is the proper way for config-related fixes?

**Comment by liaralabs** [comment]
Updates are typically for maintenance -- things that are broken or misconfigured or we maybe made a mistake on and we want to push the fix when a user runs `box update`. These should typically be coded in a way that the code doesn't run every time box update is run. For instance, when we moved Python applications out of home directories and into opt that's an update.

Upgrades are what the user calls manually to upgrade the version of their application. It doesn't often include fixes but it can. Updates run before upgrades however, so you typically can count on the application being in a specific state by the time the upgrade code is run

**Comment by rubysamurai** [comment]
Pushed new commit to deal with upgrade script and changed PR description accordingly.

**Comment by rubysamurai** [comment]
I like the idea of config re-creation, especially considering there was always a warning that the user shouldn't modify the config file.
Pushed another commit for this.

**Pull request merged**
