### PR TITLE
feat: Add jfa-go to manage Jellyfin users

### PR DESCRIPTION
**Pull request by SavageCore**
## Description
Installs [hrfee/jfa-go](https://github.com/hrfee/jfa-go) to manage Jellyfin users

## Proposed Changes:
- Add jfa-go

## Change Categories

- New feature 

## Checklist

- [x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [x] Docs have been made OR are not necessary
    - PR link: https://github.com/liaralabs/docs.swizzin.ltd/pull/136
- [x] Changes to panel have been made OR are not necessary
    - PR link:  https://github.com/swizzin/swizzin_dashboard/pull/62
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Testing was done
   - [x] Tests created or no new tests necessary
   - [x] Tests executed

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Jammy 		|			|			|			|				|
| Focal 		|			|			|			|				|
| Bionic		|			|			|			|				|
| Bullseye		|	✅		|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### CODE REVIEW

**Comment by liaralabs** [comment]
Thanks for the contribution @SavageCore.

As you are contributing a new installer flow, I must be up front to ask if you are willing to maintain your contribution moving forward. b and I have already reached saturation for what we can maintain between the two of us and are only willing to add new applications if those authors are willing to maintain their contributions moving forward.

**Comment by SavageCore** [comment]
Sorry, work got hectic! I'm happy to help when possible and @lflare take the lead on maintenance!

**Comment by brettpetch** [comment]
Going to raise this as an issue here... We should be running this application as a non-root user.
https://github.com/swizzin/swizzin/issues/1067

**Comment by SavageCore** [comment]
> Going to raise this as an issue here... We should be running this application as a non-root user. I'll likely get to a PR today. #1067

Great, if you don't get to it I should be able to do it at the weekend

**Pull request merged**
