### PR TITLE
rTorrent: Add install advisory & sink repo release

### PR DESCRIPTION
**Pull request by stickz**
This pull request adds an install advisory for rTorrent and moves the repo release to the bottom of the list.

### CODE REVIEW

**Comment by liaralabs** [comment]
I'm hesitant to push this through for the following reasons:

1. We don't recommend versions of other clients, the user is generally left to choose what's appropriate for themselves
2. It's already at the top of the list (aside from repo)
3. I disagree with 0.9.8 being the best version available for all use-cases

I would sooner rather make the changes if some updating here is requested:

- Change the whiptail box wording to something like "We recommend compiling over the distro packages"
- Move repo to the bottom of the list

**Comment by stickz** [comment]
@liaralabs What do you think about these changes? I added a new whiptail message box to advise users about compiling locally from source. And sunk the repo release to the bottom of the list. It no longer recommends a particular version as requested.

- I don't know why the `sh-checker` is failing. I tested these changes and they worked fine.
- The reason for the message box is to give users additional information that won't fit in the selection menu.

**Comment by liaralabs** [comment]
sh-checker is validating that the code meets the formatting standards -- it's less to do about syntax (though it should catch those as well). I use vs-code with the shellformat extension. The projects settings will automatically format your files correctly on save.

Otherwise, you might need to pass your files through shellformat manually with the following flags.

```
-ci -sr -i 4 -ln bash
```

**Comment by stickz** [comment]
> Otherwise, you might need to pass your files through shellformat manually with the following flags.

This is done. The file adheres to formatting standards now.

**Pull request merged**
