### PR TITLE
feat(IDE): enforce linux line breaks in vscode

### PR DESCRIPTION
**Pull request by flying-sausages**
## Description

Forces lie breaks to be `\n` instead of letting vscode guess
## Fixes issues: 
- This guy
image

## Proposed Changes:
- Force it project-wide

## Change Categories

- Contribution flow 

## Checklist

- [x] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have functionally tested the changes being introduced

## Test scenarios

N/A

### CODE REVIEW

**Comment by brettpetch** [comment]
light mode discord... what kind of monster?

but yeah, this would be good.

**Review by brettpetch — APPROVED** [review]

**Comment by userdocs** [comment]
I think this should be handled in the [.gitattributes](https://github.com/swizzin/swizzin/blob/master/.gitattributes) for the project.

**Comment by brettpetch** [comment]
> I think this should be handled in the [.gitattributes](https://github.com/swizzin/swizzin/blob/master/.gitattributes) for the project.

The reason it was suggested is because shellcheck in vscode complains about the line break type and throws errors.

**Comment by flying-sausages** [comment]
> I think this should be handled in the [.gitattributes](https://github.com/swizzin/swizzin/blob/master/.gitattributes) for the project.

We already do that

https://github.com/swizzin/swizzin/blob/master/.gitattributes

**Comment by userdocs** [comment]
https://stackoverflow.com/questions/50005806/can-i-set-the-vs-code-default-eol-based-on-file-type/50006730

Problem: auto sets to OS not filetype.

Fix: set file types manually https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_40.md#fileseol-per-language

I don't think the project file should hard set `/n`

**Comment by flying-sausages** [comment]
We already have that too

https://github.com/swizzin/swizzin/blob/master/.editorconfig

**Comment by flying-sausages** [comment]
This really is just a vs-code specific change, not something I'm deciding for the whole project.

**Comment by userdocs** [comment]
Why would you link to an extension [specific setting files](https://editorconfig.org) when I am talking about the VSCode built in method?

**Comment by flying-sausages** [comment]
The conclusion is that bakerboy is the issue. QED

**Pull request closed without merging**
