### PR TITLE
feat(flood): Jesec migration

### PR DESCRIPTION
**Pull request by flying-sausages**
## Description

New Flood installer based off the jesec fork.

## Fixes issues: 
- #545

## Proposed Changes:
- Change installer, remover, and nginx
- updater for Flood to perform the old remover and then the new installer

## Change Categories

- Bug fix 
- New feature 
- Breaking change 

## Checklist

- [ ] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [ ] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Focal 		|			|			|	🛠		|				|
| Bionic		|			|			|			|				|
| Buster		|			|			|			|				|
| Stretch		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### CODE REVIEW

**Comment by Californian** [comment]
Sorry if this comment isn't helpful (thought it might be bc of the "needs a testin" tag), but I checked out the branch and tested this and it's currently running smoothly.

**Comment by insomniac-afk** [comment]
Checked out and running smoothly, connected to qBittorrent through the WebUI port with no problems. I will keep this running for a few weeks and report any problems.


```ellis@FENRIR ~ % box install flood
INFO    Installing flood
DOCS    Further reference: https://swizzin.ltd/applications/flood
...     Installing flood
        ✔   Flood installed
...     Configuring nginx
        ✔   nginx configured
...     Giving flood permissions to ***** dir
        ✔   Done
INFO    Please create the flood account for ***** manually
...     Giving flood permissions to ***** dir
        ✔   Done
INFO    Please create the flood account for ***** manually
...     Giving flood permissions to test dir
        ✔   Done
INFO    Please create the flood account for test manually
SUCCESS Flood installed
INFO    Please finish the setup of flood in the browser

**Comment by flying-sausages** [comment]
the issue is with rtorrent unix sockets and permissions, that's where I remember it got blocked. As that's a user permission issue, this meant that the flood process would have to be able to access every user's sockets if we did not want it to run as a per-user process.

**Comment by liaralabs** [comment]
Merged in develop and refactored the code-base to utilize a central flood binary but start individual processes per user.

Tried to enable `--auth=none` to avoid double auth with htpasswd; however this method requires that you also pass command line arguments to tell the daemon what client to connect to (it only supports one "per-user" and a non-auth scheme is considered one user). I didn't feel it was a very good implementation to only support one client when swizzin has support for all the backends that flood also supports.

Thus we have two options:

1) keep the `/flood` endpoint and keep htpasswd enabled and have basic auth. Users can create sub accounts for each of their torrent clients.

2) convert the flood endpoint to the less pretty `/username/flood` endpoint, remove basic auth and let Flood handle user auth entirely.

O

**Comment by hassonipulus** [comment]
Option 1 seems optimal

**Pull request merged**
