### PR TITLE
allow access to /feed/calendar via NGINX

### PR DESCRIPTION
**Pull request by mchangrh**
## Description
Allow access to `/feed/calendar` since GCal import doesn't like inline HTTP auth

## Proposed Changes:
- Bypass authentication for path `/feed/calendar` for *arrs
  - sonarr
  - lidarr
  - radarr
  - readarr

## Change Categories

- New feature 

## Checklist

- [x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [x] Docs have been made OR are not necessary
- [x] Changes to panel have been made OR are not necessary
- [x] Code is formatted [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Shellcheck isn't screaming [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#editor-plugins-and-tooling)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Testing was done
   - [x] Tests created or no new tests necessary
   - [x] Tests executed

## Test scenarios
Since it targets nginx config, `nginx -t` was used instead and formatting was copied from previous instances of API exclusion

### CODE REVIEW

**Comment by flying-sausages** [comment]
Feel like making upgrade scripts for these? I'd check if you don't get a `grep` hit on `calendar`, then run the nginx script

**Comment by mchangrh** [comment]
> Feel like making upgrade scripts for these? I'd check if you don't get a `grep` hit on `calendar`, then run the nginx script

I'll try my best to!

**Comment by mchangrh** [comment]
Upgrade scripts done, I also changed some of the formatting for "nginx" and some other messages to be consistent across the update scripts, but didn't target any of the other ones.

**Comment by liaralabs** [comment]
Nice implementation of the update check :+1:

**Pull request merged**
