### PR TITLE
Add code to generate qr code pngs to display in panel

### PR DESCRIPTION
**Pull request by flying-sausages**
Liara pls add wg qrcodes to panel

### CODE REVIEW

**Comment by flying-sausages** [comment]
- [ ] TODO: ACLs for swizzin to read the config

**Comment by flying-sausages** [comment]
image

**Comment by flying-sausages** [comment]
I'm fine with not doing this, the docs are clear enough now on how anyone can do this anyway. Maybe something for down the road

**Comment by liaralabs** [comment]
To be clear, I'm not against this, but my concern is trying to balance some people's fear that the panel may have too many permissions and that the QR code contains private keys. On a multi-user server this amounts to the swizzin user having potential access to any of the wg tunnels.

We already set the ACLs so this is generally a larger question about how permissive we are okay with the swizzin user being.

**Comment by flying-sausages** [comment]
Yeah no worries, I don't have the bandwidth to make suggestions on this either rn. I'll move it to feathub

**Pull request closed without merging**
