### PR TITLE
Changed boost download

### PR DESCRIPTION
**Pull request by siedenburg2**
Swapped boost download url because the account on the main site is deactivated, also changed wget to curl to download more than an html file from sourceforge

## Description

The boost download redirects to landing.jfrog.com/reactivate-server/boostorg, wget loads a html page and because it downloads something the fallback isn't working, could be fixed, but is a bit more work, so I canged the dl sites for now as a quick fix. Also changed wget to curl because I got problems with wget and loading from sourceforge.

Also: Is there a reason why boost 1.75 is still in use while there was a boost 1.84 release this december? 1.75 was released in december 2020. Didn't change version in case of breaking stuff.

## Fixes issues: 
- Un-tracked issue...

## Proposed Changes:
- Changed boost download method in libtorrent function

## Change Categories

- Bug fix               
- Change in `functions` 

## Checklist

- [x] Branch was made off the `develop` branch and the PR is targetting the `develop` branch
- [x] Docs have been made OR are not necessary
    - PR link: 
- [x] Changes to panel have been made OR are not necessary
    - PR link: 
- [x] Code conforms to project structure [(See more)](https://swizzin.ltd/dev/structure)
- [x] Prints to terminal are handled [(See more)](https://github.com/swizzin/swizzin/blob/master/CONTRIBUTING.md#printing-into-the-terminal)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Testing was done
   - [x] Tests created or no new tests necessary
   - [x] Tests executed

### Architectures

|   			| `amd64` 	| `armhf` 	| `arm64` 	| Unspecified 	|
|--------		|-------- 	|-------- 	|-------- 	|----------		|
| Jammy 		|	✅		|			|			|				|
| Focal 		|			|			|			|				|
| Bookworm      |    ✅       |           |           |               |
| Bullseye		|			|			|			|				|
| Buster		|			|			|			|				|
| Raspbian  	|	⚫️		|			|	⚫️		|	⚫️			|

### CODE REVIEW

**Comment by liaralabs** [comment]
I think attempting to make the fallback mechanism robust would be the preferred play here. Sourceforge isn't the primary mirror and I'm not interested in swapping the mirrors to reflect that.

Reason being, the upstream issues have already been resolved without intervention from us. Making snap decisions such as this to swap the mirrors does fix the issue in the interim but doesn't actually address the real issue here: fallback was temporarily needed and didn't properly trigger due to the command not actually failing (receiving a redirect instead of a download still give us an exit code of 0 with curl/wget)

**Review by siedenburg2 — COMMENTED** [review]
Changed the simple server swap to a solution where the server tries to download from any url in the array and if the file on the server isn't the right mimetype ("application/octet-stream" or "application/x-gzip") or if the server is offline etc, it's counted to an error counter and if every url in the array fails the installation will be aborted.

**Comment by liaralabs** [comment]
Awesome stuff, thank you!

**Comment by Oudinunit** [comment]
Ok ka Thanks you ka my family

เมื่อ อา. 14 ม.ค. 2567 เวลา 01:49 liaralabs ***@***.***>
เขียนว่า:

**Pull request merged**
